### PR TITLE
Change repository location from sstrecker to gi-ev

### PR DESCRIPTION
**Pull request by koppor**
This proposes a new repository location for this latex template. I propose https://github.com/gi-ev/ as new home as that organization hosts other templates by GI e.V. @sieversMartin has the appropriate rights to move this repository to there.

I did not rename the repository itself. I know that one is called "LNI" and this one "emisa-latex-package". Maybe, we should rename "LNI" to "LNI-latex-package", but this is another issue. For now, I think, the inconsistent naming does not cause much confusion.

### CODE REVIEW

**Comment by sieversMartin** [comment]
@sstrecker What do you think? I don't want to decide on this.

**Comment by sieversMartin** [comment]
I just realised, that I am _not_ allowed to transfer the repository. Either @sstrecker has to do it (or any other admin) or I have to become admin myself.

**Comment by sstrecker** [comment]
The interesting question now is: How do I make you admin of this repo?

**Comment by sieversMartin** [comment]
We need user "emisa-journal"

**Pull request merged**
